"use client";
import { useEffect, useState } from "react";
import { Copy, Plus, Check, X } from "lucide-react";

type Campaign={id:string;name:string;slug:string;clicks:number;createdAt:string;link:string;registrations:number};
type Referral={id:string;name:string;createdAt:string;isPremium:boolean;campaignId:string|null};
export default function AffiliateCampaignsClient({referral}:{referral:string}){
 const [items,setItems]=useState<Campaign[]>([]); const [referrals,setReferrals]=useState<Referral[]>([]); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [copied,setCopied]=useState(""); const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/affiliate/campaigns',{cache:'no-store'}); if(r.ok){const d=await r.json();setItems(d.campaigns||[]);setReferrals(d.referrals||[])}};
 useEffect(()=>{void load()},[]);
 const copy=async(v:string,id:string)=>{await navigator.clipboard.writeText(v);setCopied(id);setTimeout(()=>setCopied(""),1500)};
 const create=async()=>{if(!name.trim())return;setBusy(true);const r=await fetch('/api/affiliate/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});setBusy(false);if(r.ok){setName('');setOpen(false);void load()}};
 return <div className="space-y-4">
  <div className="rounded-[18px] border border-sky-400/15 bg-[#071522] p-5">
   <div className="text-xs font-black uppercase tracking-wider text-sky-300">Twój link polecający</div>
   <div className="mt-3 flex flex-col gap-2 md:flex-row"><div className="min-w-0 flex-1 break-all rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-xs text-sky-200">{referral}</div><button onClick={()=>copy(referral,'main')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-sky-500 px-4 py-3 text-xs font-black hover:bg-sky-400">{copied==='main'?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied==='main'?'Skopiowano':'Kopiuj link'}</button></div>
  </div>
  <div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Kampanie polecające</h2><p className="text-xs text-slate-400">Twórz osobne linki dla TikTok, Instagram, YouTube lub konkretnego bannera.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-xs font-black"><Plus className="h-4 w-4"/>Utwórz kampanię</button></div>
  {open&&<div className="rounded-[18px] border border-cyan-400/25 bg-[#071522] p-5"><div className="flex items-center justify-between"><b>Nowa kampania</b><button onClick={()=>setOpen(false)}><X className="h-4 w-4"/></button></div><div className="mt-3 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void create()}} placeholder="np. TikTok Wrzesień" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-cyan-400/40"/><button disabled={busy||!name.trim()} onClick={()=>void create()} className="rounded-xl bg-cyan-500 px-5 text-xs font-black disabled:opacity-40">{busy?'Tworzę…':'Utwórz'}</button></div></div>}
  <div className="rounded-[18px] border border-sky-400/15 bg-[#071522] p-5"><div className="text-xs font-black uppercase tracking-wider text-sky-300">Zarejestrowane osoby z Twojego linku</div><div className="mt-3 space-y-2">{referrals.length?referrals.map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-black/15 px-3 py-2"><div><div className="text-xs font-bold">{r.name}</div><div className="text-[9px] text-slate-500">{new Date(r.createdAt).toLocaleDateString('pl-PL')}</div></div><span className={r.isPremium?"rounded-lg bg-emerald-500/10 px-2 py-1 text-[9px] font-black text-emerald-300":"rounded-lg bg-sky-500/10 px-2 py-1 text-[9px] font-black text-sky-300"}>{r.isPremium?'PREMIUM':'ZAREJESTROWANY'}</span></div>):<div className="text-xs text-slate-500">Brak rejestracji z linku polecającego.</div>}</div></div>
  <div className="grid gap-3">{items.length?items.map(c=><div key={c.id} className="rounded-[18px] border border-sky-400/15 bg-[#071522] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">{c.name}</div><div className="mt-1 text-[10px] text-slate-500">Kliknięcia: {c.clicks} • Rejestracje: {c.registrations}</div></div><button onClick={()=>copy(c.link,c.id)} className="inline-flex items-center gap-2 rounded-xl border border-sky-400/20 bg-sky-500/10 px-3 py-2 text-xs font-bold text-sky-200">{copied===c.id?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied===c.id?'Skopiowano':'Kopiuj link'}</button></div><div className="mt-3 break-all rounded-lg bg-black/20 p-2 text-[11px] text-slate-400">{c.link}</div></div>):<div className="rounded-[18px] border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">Nie masz jeszcze kampanii. Kliknij „Utwórz kampanię”.</div>}</div>
 </div>
}
