"use client";

import React from "react";
import type { CandlestickData, UTCTimestamp } from "lightweight-charts";
import MarketChart, { type AnalysisLine, type AnalysisZone, type Levels } from "@/components/MarketChart";
import { Activity, BarChart3, CheckCircle2, Crosshair, Gauge, ScanSearch, Target, Zap } from "lucide-react";

type Mode = "SNIPER" | "PATTERN";
type TF = "M1" | "M5" | "M15" | "H1" | "H4";
const TFS: TF[] = ["M1","M5","M15","H1","H4"];
const INTERVAL: Record<TF,string> = { M1:"1min", M5:"5min", M15:"15min", H1:"1h", H4:"4h" };
const SYMBOLS = ["EURUSD","GBPUSD","USDJPY","USDCHF","AUDUSD","NZDUSD","USDCAD","EURJPY","GBPJPY","XAUUSD"];
const PATTERNS = ["Head & Shoulders","Inverse H&S","Double Top","Double Bottom","Ascending Triangle","Descending Triangle","Symmetrical Triangle","Bull Flag","Bear Flag","Pennant","Rising Wedge","Falling Wedge","Rectangle"];

type C = CandlestickData & { open:number; high:number; low:number; close:number; time:UTCTimestamp };
const n=(v:unknown)=>Number(v);
function emaSeries(values:number[], period:number){ if(!values.length)return []; const k=2/(period+1); const out:number[]=[]; let e=values[0]; for(const v of values){e=v*k+e*(1-k);out.push(e);} return out; }
function ema(values:number[], period:number){ return emaSeries(values,period).at(-1)??0; }
function atr(c:C[], p=14){ if(c.length<2)return 0; const a=c.slice(-p-1); let s=0,k=0; for(let i=1;i<a.length;i++){s+=Math.max(a[i].high-a[i].low,Math.abs(a[i].high-a[i-1].close),Math.abs(a[i].low-a[i-1].close));k++;} return k?s/k:0; }
function rsiSeries(c:C[], p=14){ const out=Array(c.length).fill(50); if(c.length<=p)return out; let g=0,l=0; for(let i=1;i<=p;i++){const d=c[i].close-c[i-1].close;g+=Math.max(d,0);l+=Math.max(-d,0);} g/=p;l/=p; for(let i=p;i<c.length;i++){if(i>p){const d=c[i].close-c[i-1].close;g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;} out[i]=l===0?100:100-(100/(1+g/l));} return out; }
function fmt(symbol:string,v:number){ return v.toFixed(symbol.includes("JPY")?3:symbol==="XAUUSD"?2:5); }

function detectZones(c:C[]):AnalysisZone[]{
  if(c.length<30)return []; const out:AnalysisZone[]=[]; const a=atr(c,14)||1;
  for(let i=Math.max(2,c.length-120);i<c.length-2;i++){const base=c[i],next=c[i+1];const body=Math.abs(next.close-next.open);if(body<a*1.1)continue;
    if(next.close>next.open&&next.close>base.high)out.push({id:`d-${base.time}`,kind:"DEMAND",from:base.low,to:Math.max(base.open,base.close),startTime:base.time,label:"DEMAND ZONE"});
    if(next.close<next.open&&next.close<base.low)out.push({id:`s-${base.time}`,kind:"SUPPLY",from:Math.min(base.open,base.close),to:base.high,startTime:base.time,label:"SUPPLY ZONE"});
  } return out.slice(-4);
}
function pivots(c:C[], high:boolean){const r:{i:number;p:number;t:UTCTimestamp}[]=[];for(let i=2;i<c.length-2;i++){const v=high?c[i].high:c[i].low;let ok=true;for(let j=i-2;j<=i+2;j++)if(j!==i&&(high?c[j].high>=v:c[j].low<=v))ok=false;if(ok)r.push({i,p:v,t:c[i].time});}return r;}
type PatternResult={name:string;direction:"BUY"|"SELL";lines:AnalysisLine[];quality:number;breakout:boolean;retest:boolean};
function detectPattern(c:C[]):PatternResult{
 const hi=pivots(c,true).slice(-6),lo=pivots(c,false).slice(-6),lines:AnalysisLine[]=[]; if(c.length<30||hi.length<2||lo.length<2)return{name:"Scanning…",direction:"BUY",lines,quality:0,breakout:false,retest:false};
 const h1=hi.at(-2)!,h2=hi.at(-1)!,l1=lo.at(-2)!,l2=lo.at(-1)!,a=atr(c,14)||1,tol=a*.5,last=c.at(-1)!;
 const L=(id:string,A:{t:UTCTimestamp;p:number},B:{t:UTCTimestamp;p:number},label?:string)=>lines.push({id,fromTime:A.t,fromPrice:A.p,toTime:B.t,toPrice:B.p,label});
 if(hi.length>=3&&lo.length>=2){const h0=hi.at(-3)!; if(h1.p>h0.p+a*.35&&h1.p>h2.p+a*.35&&Math.abs(h0.p-h2.p)<a*.9){L("hs1",h0,h1,"LEFT SHOULDER → HEAD");L("hs2",h1,h2,"HEAD → RIGHT SHOULDER");L("neck",l1,l2,"NECKLINE");const br=last.close<l2.p;return{name:"Head & Shoulders",direction:"SELL",lines,quality:br?93:86,breakout:br,retest:br&&last.high>=l2.p-a*.25};}}
 if(Math.abs(h2.p-h1.p)<tol&&l2.p>l1.p){L("res",h1,h2,"RESISTANCE");L("rise",l1,l2,"ASCENDING TRENDLINE");const br=last.close>h2.p;return{name:"Ascending Triangle",direction:"BUY",lines,quality:br?94:89,breakout:br,retest:br&&last.low<=h2.p+a*.3};}
 if(Math.abs(l2.p-l1.p)<tol&&h2.p<h1.p){L("sup",l1,l2,"SUPPORT");L("fall",h1,h2,"DESCENDING TRENDLINE");const br=last.close<l2.p;return{name:"Descending Triangle",direction:"SELL",lines,quality:br?93:88,breakout:br,retest:br&&last.high>=l2.p-a*.3};}
 if(Math.abs(h2.p-h1.p)<tol){L("top",h1,h2,"DOUBLE TOP");L("neck",l1,l2,"NECKLINE");const br=last.close<l2.p;return{name:"Double Top",direction:"SELL",lines,quality:br?92:84,breakout:br,retest:br&&last.high>=l2.p-a*.3};}
 if(Math.abs(l2.p-l1.p)<tol){L("bottom",l1,l2,"DOUBLE BOTTOM");L("neck",h1,h2,"NECKLINE");const br=last.close>h2.p;return{name:"Double Bottom",direction:"BUY",lines,quality:br?92:84,breakout:br,retest:br&&last.low<=h2.p+a*.3};}
 L("upper",h1,h2,"UPPER TRENDLINE");L("lower",l1,l2,"LOWER TRENDLINE"); const converging=h2.p<h1.p&&l2.p>l1.p; const name=converging?"Symmetrical Triangle":h2.p<h1.p?"Falling Wedge":"Rising Wedge"; const dir=name==="Rising Wedge"?"SELL":"BUY"; return{name,direction:dir,lines,quality:78,breakout:false,retest:false};
}
async function load(symbol:string,tf:TF):Promise<C[]>{const q=new URLSearchParams({path:"/time_series",symbol:symbol==="XAUUSD"?"XAU/USD":`${symbol.slice(0,3)}/${symbol.slice(3)}`,interval:INTERVAL[tf],outputsize:"260",format:"JSON"});const r=await fetch(`/api/twelve-data?${q}`,{cache:"no-store"});const d=await r.json();if(!r.ok||d?.status==="error")throw new Error(d?.message||"Nie udało się pobrać świec");return(d.values??[]).map((x:any)=>({time:Math.floor(Date.parse(String(x.datetime).replace(" ","T")+(String(x.datetime).includes("Z")?"":"Z"))/1000)as UTCTimestamp,open:n(x.open),high:n(x.high),low:n(x.low),close:n(x.close)})).filter((x:C)=>Number.isFinite(Number(x.time))&&Number.isFinite(x.close)).sort((a:C,b:C)=>Number(a.time)-Number(b.time));}

function Oscillator({values,times,kind,range,crosshair}:{values:number[];times:number[];kind:"SNIPER"|"RSI";range:{from:number;to:number}|null;crosshair:number|null}){const pairs=values.map((v,i)=>({v,t:times[i]})).filter(x=>!range||(x.t>=range.from&&x.t<=range.to));const shown=(pairs.length?pairs:pairs.slice(-90));const data=shown.map(x=>x.v);if(!data.length)return null;const w=1000,h=145,p=12;const min=kind==="RSI"?0:Math.min(...data,0),max=kind==="RSI"?100:Math.max(...data,0);const y=(v:number)=>p+(max-v)/(max-min||1)*(h-p*2);const pts=data.map((v,i)=>`${(i/(Math.max(1,data.length-1)))*w},${y(v)}`).join(" ");const zero=y(kind==="RSI"?50:0);const cx=crosshair&&shown.length?Math.max(0,Math.min(w,((crosshair-shown[0].t)/(shown.at(-1)!.t-shown[0].t||1))*w)):null;return <div className="relative h-[145px] overflow-hidden border-t border-slate-700/70 bg-[#061225]"><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" className="h-full w-full"><line x1="0" x2={w} y1={zero} y2={zero} stroke="#64748b" strokeDasharray="5 5" opacity=".5"/>{kind==="RSI"&&<><line x1="0" x2={w} y1={y(70)} y2={y(70)} stroke="#64748b" strokeDasharray="4 5" opacity=".45"/><line x1="0" x2={w} y1={y(30)} y2={y(30)} stroke="#64748b" strokeDasharray="4 5" opacity=".45"/></>}{kind==="SNIPER"&&data.map((v,i)=>{const x=i/data.length*w;return <rect key={i} x={x} width={Math.max(2,w/data.length-2)} y={Math.min(y(v),zero)} height={Math.max(1,Math.abs(y(v)-zero))} fill={v>=0?"#10b981":"#ef4444"} opacity=".9"/>})}{cx!==null&&<line x1={cx} x2={cx} y1="0" y2={h} stroke="#94a3b8" strokeDasharray="3 3" opacity=".7"/>}<polyline points={pts} fill="none" stroke={kind==="RSI"?"#8b5cf6":"#e2e8f0"} strokeWidth="2"/></svg><div className="absolute left-3 top-2 text-xs font-bold">{kind==="RSI"?"RSI 14":"Sniperlator"} <span className={kind==="RSI"?"text-violet-400":"text-emerald-400"}>{data.at(-1)?.toFixed(2)}</span></div>{kind==="RSI"&&<div className="absolute right-2 top-2 text-[10px] text-slate-400">70<br/><span className="leading-[55px]">50</span><br/>30</div>}</div>}
function MiniPattern({name}:{name:string}){const map:Record<string,string>={"Double Top":"5,34 22,10 39,34 56,10 74,35","Double Bottom":"5,10 22,34 39,10 56,34 74,9","Head & Shoulders":"4,34 18,18 30,30 42,5 54,30 66,18 78,34","Inverse H&S":"4,8 18,24 30,12 42,37 54,12 66,24 78,8","Ascending Triangle":"4,35 78,12 10,12 78,12","Descending Triangle":"4,10 78,35 10,35 78,35","Symmetrical Triangle":"4,8 76,25 4,40 76,25","Bull Flag":"4,36 28,8 42,18 62,13 42,30 62,25 78,6","Bear Flag":"4,6 28,34 42,24 62,29 42,12 62,17 78,38","Pennant":"4,34 28,8 44,15 66,23 44,31 66,23 78,8","Rising Wedge":"4,36 74,12 4,27 74,7","Falling Wedge":"4,8 74,32 4,17 74,37","Rectangle":"5,10 75,10 75,35 5,35 5,10"};return <svg viewBox="0 0 82 45" className="h-10 w-full"><polyline points={map[name]||map.Rectangle} fill="none" stroke="#22d3ee" strokeWidth="2"/><line x1="4" y1="40" x2="78" y2="5" stroke="#22c55e" strokeWidth="1.5" opacity=".65"/></svg>}
function Metric({icon,title,value,sub}:{icon:React.ReactNode;title:string;value:string;sub:string}){return <div className="rounded-xl border border-slate-700/70 bg-[#07152b] p-3"><div className="flex items-center gap-2 text-[10px] font-bold uppercase text-slate-400">{icon}{title}</div><div className="mt-1 text-lg font-black text-emerald-400">{value}</div><div className="text-[10px] text-slate-500">{sub}</div></div>}

export default function AdvancedScannerPage({mode}:{mode:Mode}){
 const [symbol,setSymbol]=React.useState("EURUSD"),[tf,setTf]=React.useState<TF>("M5"),[candles,setCandles]=React.useState<C[]>([]),[error,setError]=React.useState(""); const [visibleRange,setVisibleRange]=React.useState<{from:number;to:number}|null>(null); const [crosshairTime,setCrosshairTime]=React.useState<number|null>(null);
 React.useEffect(()=>{let alive=true;const run=async()=>{try{const x=await load(symbol,tf);if(alive){setCandles(x);setError("")}}catch(e:any){if(alive)setError(e?.message||"Błąd danych")}};run();const id=setInterval(run,30000);return()=>{alive=false;clearInterval(id)}},[symbol,tf]);
 const zones=React.useMemo(()=>mode==="SNIPER"?detectZones(candles):[],[mode,candles]),pattern=React.useMemo(()=>detectPattern(candles),[candles]);
 const closes=candles.map(x=>x.close),last=candles.at(-1),e50=ema(closes,50),e200=ema(closes,200),trend=last?(last.close>e50&&e50>e200?"BUY":last.close<e50&&e50<e200?"SELL":"WAIT"):"WAIT";
 const a=atr(candles,14)||1,activeZone=last&&zones.filter(z=>last.close>=z.from-a*.25&&last.close<=z.to+a*.25).at(-1); const fast=emaSeries(closes,8),slow=emaSeries(closes,21),raw=closes.map((_,i)=>((fast[i]??0)-(slow[i]??0))/(a||1)); const sniper=emaSeries(raw,3); const momentum=(sniper.at(-1)??0)>(sniper.at(-3)??0); const rsi=rsiSeries(candles,14);
 const direction=mode==="PATTERN"?pattern.direction:(activeZone?.kind==="DEMAND"?"BUY":activeZone?.kind==="SUPPLY"?"SELL":trend==="SELL"?"SELL":"BUY"); const confirmations=mode==="PATTERN"?[pattern.quality>=70,pattern.lines.length>0,pattern.breakout,pattern.retest]:[trend===direction,!!activeZone,direction==="BUY"?momentum:!momentum]; const score=confirmations.filter(Boolean).length; const ready=mode==="PATTERN"?pattern.quality>=80&&pattern.lines.length>0:score===3;
 const risk=last?a:0,entry=last?.close??0,sl=direction==="BUY"?entry-risk:entry+risk,tps=direction==="BUY"?[entry+risk*1.5,entry+risk*2.5]:[entry-risk*1.5,entry-risk*2.5],levels:Levels|undefined=last?{side:direction,entry,sl,tps,rr:2.5}:undefined; const strength=Math.max(0,Math.min(100,Math.round(Math.abs(e50-e200)/(a||1)*100))); const volatility=Math.max(0,Math.min(100,Math.round(a/(last?.close||1)*10000)));
 return <main className="min-h-screen bg-[#020817] p-3 text-white md:p-5"><div className="mx-auto max-w-[1900px] space-y-3">
  <header className="flex flex-col gap-3 rounded-2xl border border-sky-500/30 bg-[#07152b] p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3">{mode==="SNIPER"?<Target className="h-8 w-8 text-cyan-400"/>:<ScanSearch className="h-8 w-8 text-cyan-400"/>}<div><h1 className="text-2xl font-black">{mode==="SNIPER"?"SNIPER SCANNER":"CHART PATTERN SCANNER"}</h1><p className="text-xs text-slate-400">{mode==="SNIPER"?"PRECISION SETUPS · DEMAND/SUPPLY · MOMENTUM":"REAL PATTERNS · BREAKOUT · RETEST · TRADE LEVELS"}</p></div></div><div className="flex flex-wrap gap-2">{TFS.map(x=><button key={x} onClick={()=>setTf(x)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${tf===x?"border-cyan-400 bg-cyan-500/20 text-cyan-300":"border-slate-700 bg-slate-900"}`}>{x}</button>)}</div></header>
  <div className="grid gap-3 xl:grid-cols-[260px_minmax(0,1fr)_300px]"><aside className="rounded-2xl border border-slate-800 bg-[#07152b] p-3"><div className="mb-3 text-xs font-bold text-slate-400">INSTRUMENTY</div>{SYMBOLS.map(x=><button key={x} onClick={()=>setSymbol(x)} className={`mb-1 flex w-full items-center justify-between rounded-lg px-3 py-2 text-sm ${symbol===x?"bg-sky-500/20 text-sky-300":"hover:bg-slate-800"}`}><span>{x}</span><span className="text-[10px] text-slate-500">{tf}</span></button>)}</aside>
  <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-800 bg-[#07152b]"><div className="flex items-center justify-between px-4 py-3"><b>{symbol} · {tf}</b><span className="text-xs text-slate-400">{error||"LIVE · auto refresh 30s"}</span></div><MarketChart symbol={symbol} tf={tf} candles={candles} height={mode==="PATTERN"?555:555} showEma emaConfigs={[{period:50,color:"#0ea5e9",width:2},{period:200,color:"#f59e0b",width:2}]} showTradeLines={ready} levels={ready?levels:undefined} analysisZones={zones} analysisLines={mode==="PATTERN"?pattern.lines:[]} onVisibleTimeRangeChange={setVisibleRange} onCrosshairTimeChange={setCrosshairTime} /><Oscillator values={mode==="SNIPER"?sniper:rsi} times={candles.map(c=>Number(c.time))} kind={mode==="SNIPER"?"SNIPER":"RSI"} range={visibleRange} crosshair={crosshairTime}/></section>
  <aside className="space-y-3"><div className={`rounded-2xl border p-4 ${ready?"border-emerald-500/50 bg-emerald-500/10":"border-amber-500/30 bg-amber-500/5"}`}><div className="text-xs text-slate-400">STATUS</div><div className={`mt-1 text-2xl font-black ${ready?"text-emerald-400":"text-amber-300"}`}>{ready?"READY":"SCANNING"}</div></div><div className="rounded-2xl border border-slate-800 bg-[#07152b] p-4"><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-400">Instrument</span><b>{symbol}</b></div><div className="flex justify-between"><span className="text-slate-400">Kierunek</span><b className={direction==="BUY"?"text-emerald-400":"text-red-400"}>{direction}</b></div>{mode==="PATTERN"?<><div className="flex justify-between"><span className="text-slate-400">Pattern</span><b>{pattern.name}</b></div><div className="flex justify-between"><span className="text-slate-400">Quality</span><b>{pattern.quality}%</b></div></>:<div className="flex justify-between"><span className="text-slate-400">Potwierdzenia</span><b>{score}/3</b></div>}{last&&<><hr className="border-slate-800"/><div className="flex justify-between"><span>Entry</span><b>{fmt(symbol,entry)}</b></div><div className="flex justify-between"><span>SL</span><b className="text-red-400">{fmt(symbol,sl)}</b></div><div className="flex justify-between"><span>TP1</span><b className="text-emerald-400">{fmt(symbol,tps[0])}</b></div><div className="flex justify-between"><span>TP2</span><b className="text-emerald-400">{fmt(symbol,tps[1])}</b></div><div className="flex justify-between"><span>RR</span><b>1 : 2.5</b></div></>}</div></div><div className="rounded-2xl border border-slate-800 bg-[#07152b] p-4"><div className="mb-3 text-xs font-bold text-slate-400">{mode==="SNIPER"?"CONFLUENCE 3/3":"PATTERN CHECK"}</div>{(mode==="SNIPER"?["Trend EMA 50/200","Demand / Supply Zone","Sniperlator Momentum"]:["Pattern detected","Structure drawn","Breakout confirmed","Retest completed"]).map((x,i)=><div key={x} className="mb-2 flex items-center gap-2 text-sm"><CheckCircle2 className={`h-4 w-4 ${confirmations[i]?"text-emerald-400":"text-slate-600"}`}/>{x}</div>)}</div></aside></div>
  {mode==="SNIPER"?<div className="grid gap-3 md:grid-cols-4"><Metric icon={<TrendingIcon/>} title="Market Bias" value={trend==="BUY"?"BULLISH":trend==="SELL"?"BEARISH":"NEUTRAL"} sub={`Trend strength ${strength}%`}/><Metric icon={<Activity className="h-4 w-4"/>} title="Sniperlator" value={(sniper.at(-1)??0).toFixed(3)} sub={momentum?"Turning Up":"Turning Down"}/><Metric icon={<Gauge className="h-4 w-4"/>} title="Volatility" value={volatility>70?"HIGH":volatility>35?"NORMAL":"LOW"} sub={`Volatility ${volatility}%`}/><Metric icon={<Zap className="h-4 w-4"/>} title="Sniper Pro Tip" value="KEY LEVELS" sub="Zone + trend + momentum = setup"/></div>:<div className="rounded-2xl border border-slate-800 bg-[#07152b] p-3"><div className="mb-2 flex items-center gap-2 text-xs font-black text-slate-300"><BarChart3 className="h-4 w-4 text-cyan-400"/>SUPPORTED PATTERNS</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{PATTERNS.map(p=><div key={p} className={`rounded-lg border p-2 text-center ${p===pattern.name?"border-cyan-400 bg-cyan-500/10":"border-slate-800 bg-[#061225]"}`}><MiniPattern name={p}/><div className="mt-1 text-[9px] text-slate-300">{p}</div></div>)}</div></div>}
 </div></main>;
}
function TrendingIcon(){return <Crosshair className="h-4 w-4"/>}
