"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { setCurrentStorageUser } from "@/lib/userScopedStorage";
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, TrendingUp, UserRound, X } from "lucide-react";

type LoginResponse = { error?: string; details?: string; requiresTwoFactor?: boolean; user?: { id: string; email: string; name: string | null; role: string } };

export default function LoginPage() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false);
  const [remember,setRemember]=useState(true); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const [pin,setPin]=useState(["","","",""]); const pinRefs=useRef<Array<HTMLInputElement|null>>([]); const [pinLoading,setPinLoading]=useState(false);
  const [twoFactorOpen,setTwoFactorOpen]=useState(false); const [twoFactorCode,setTwoFactorCode]=useState(""); const [twoFactorLoading,setTwoFactorLoading]=useState(false); const [twoFactorError,setTwoFactorError]=useState("");
  const [createOpen,setCreateOpen]=useState(false); const [createPassword,setCreatePassword]=useState(""); const [newPin,setNewPin]=useState(""); const [confirmPin,setConfirmPin]=useState(""); const [createLoading,setCreateLoading]=useState(false); const [createError,setCreateError]=useState(""); const [createSuccess,setCreateSuccess]=useState("");

  async function handleLogin(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");try{const res=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({email,password,remember})});const data=(await res.json().catch(()=>null)) as LoginResponse|null;if(!res.ok){setError(data?.details||data?.error||`Błąd logowania (${res.status})`);return;}if(data?.requiresTwoFactor){setTwoFactorError("");setTwoFactorCode("");setTwoFactorOpen(true);return;}if(data?.user?.id)setCurrentStorageUser(data.user.id);window.location.replace("/dashboard");}catch(err){setError(err instanceof Error?err.message:"Problem z połączeniem z serwerem");}finally{setLoading(false)}}
  function updatePin(index:number,value:string){const digit=value.replace(/\D/g,"").slice(-1);const next=[...pin];next[index]=digit;setPin(next);if(digit&&index<3)pinRefs.current[index+1]?.focus()}
  function pinKey(index:number,e:React.KeyboardEvent<HTMLInputElement>){if(e.key==="Backspace"&&!pin[index]&&index>0)pinRefs.current[index-1]?.focus()}
  async function handlePinLogin(){setError("");if(!email.trim()){setError("Wpisz e-mail w polu powyżej, aby zalogować się PIN-em.");return;}const code=pin.join("");if(!/^\d{4}$/.test(code)){setError("Wprowadź 4-cyfrowy PIN.");return;}setPinLoading(true);try{const res=await fetch("/api/login/pin",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({email,pin:code})});const data=(await res.json().catch(()=>null)) as LoginResponse|null;if(!res.ok){setError(data?.error||"Nie udało się zalogować PIN-em");return;}if(data?.requiresTwoFactor){setTwoFactorError("");setTwoFactorCode("");setTwoFactorOpen(true);return;}if(data?.user?.id)setCurrentStorageUser(data.user.id);window.location.replace("/dashboard");}finally{setPinLoading(false)}}
  async function verifyTwoFactor(){setError("");setTwoFactorError("");if(!/^\d{6}$/.test(twoFactorCode)){setTwoFactorError("Wprowadź 6-cyfrowy kod z aplikacji Authenticator.");return;}setTwoFactorLoading(true);try{const res=await fetch("/api/2fa/verify-login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({code:twoFactorCode})});const data=(await res.json().catch(()=>null)) as LoginResponse|null;if(!res.ok){setTwoFactorError(data?.error||"Nieprawidłowy kod 2FA");return;}if(data?.user?.id)setCurrentStorageUser(data.user.id);window.location.replace("/dashboard");}finally{setTwoFactorLoading(false)}}
  async function createPin(){setCreateError("");setCreateSuccess("");if(!email.trim()){setCreateError("Najpierw wpisz e-mail na ekranie logowania.");return;}if(!createPassword){setCreateError("Podaj hasło do konta.");return;}if(!/^\d{4}$/.test(newPin)){setCreateError("PIN musi mieć dokładnie 4 cyfry.");return;}if(newPin!==confirmPin){setCreateError("Kody PIN nie są takie same.");return;}setCreateLoading(true);try{const res=await fetch("/api/pin/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password:createPassword,pin:newPin})});const data=await res.json().catch(()=>null);if(!res.ok){setCreateError(data?.error||"Nie udało się utworzyć PIN-u");return;}setCreateSuccess("PIN został utworzony. Możesz się nim teraz zalogować.");setPin(newPin.split(""));setCreatePassword("");setNewPin("");setConfirmPin("");setTimeout(()=>setCreateOpen(false),1000);}finally{setCreateLoading(false)}}

  return <main className="relative min-h-screen overflow-hidden bg-[#031225] text-white">
    <div className="pointer-events-none fixed inset-0 z-0 bg-cover bg-center" style={{backgroundImage:"linear-gradient(rgba(2,8,23,.30),rgba(2,8,23,.55)),url('/login-bg.png')"}}/>
    <div className="relative z-10 flex min-h-screen items-center justify-center px-4 py-8"><div className="w-full max-w-[735px] rounded-[34px] border border-cyan-300/80 bg-[linear-gradient(145deg,rgba(5,28,59,.91),rgba(2,16,35,.95))] p-6 shadow-[0_0_60px_rgba(0,174,255,.32)] backdrop-blur-xl sm:p-10">
      <div className="mb-7 flex justify-center"><img src="/fx-trade-professional-trading.png" alt="FX Trade" className="h-auto w-full max-w-[470px] object-contain drop-shadow-[0_0_25px_rgba(37,99,235,.35)]"/></div>
      <form onSubmit={handleLogin} className="space-y-4">
        <div><label className="mb-2 flex items-center gap-2 text-sm font-semibold"><Mail className="h-4 w-4 text-cyan-400"/>E-mail</label><div className="relative"><UserRound className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-sky-300"/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Wprowadź swój e-mail" className="w-full rounded-xl border border-sky-400/65 bg-[#06172f]/90 px-12 py-4 text-[16px] outline-none focus:border-cyan-300" required/></div></div>
        <div><div className="mb-2 flex justify-between"><label className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="h-4 w-4 text-cyan-400"/>Hasło</label><Link href="/forgot-password" className="text-xs font-semibold text-cyan-300">Nie pamiętasz hasła?</Link></div><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-sky-300"/><input type={showPassword?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Wprowadź hasło" className="w-full rounded-xl border border-sky-400/65 bg-[#06172f]/90 px-12 py-4 pr-14 text-[16px] outline-none focus:border-cyan-300" required/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-300">{showPassword?<EyeOff className="h-5 w-5"/>:<Eye className="h-5 w-5"/>}</button></div></div>
        <label className="flex w-fit cursor-pointer items-center gap-3 text-sm"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="h-5 w-5 accent-sky-500"/>Zapamiętaj mnie</label>
        {error?<div className="rounded-xl border border-rose-400/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>:null}
        <button type="submit" disabled={loading} className="flex w-full items-center justify-center gap-3 rounded-xl border border-cyan-300/25 bg-[linear-gradient(90deg,#12c7e9,#168ef0_55%,#2454ff)] py-4 text-[17px] font-bold shadow-[0_0_30px_rgba(14,165,233,.28)] hover:brightness-110 disabled:opacity-60"><TrendingUp className="h-5 w-5"/>{loading?"Logowanie...":"Zaloguj się"}</button>
      </form>
      <div className="my-7 flex items-center gap-4"><div className="h-px flex-1 bg-sky-300/35"/><span className="text-[11px] font-semibold text-slate-400">LUB</span><div className="h-px flex-1 bg-sky-300/35"/></div>
      <div className="text-center"><h2 className="flex items-center justify-center gap-2 text-lg font-semibold"><LockKeyhole className="h-5 w-5 text-cyan-400"/>Zaloguj się kodem PIN</h2><p className="mt-1 text-xs text-slate-300">Wprowadź 4-cyfrowy kod PIN</p><div className="mt-4 flex justify-center gap-3">{pin.map((v,i)=><input key={i} ref={el=>{pinRefs.current[i]=el}} inputMode="numeric" maxLength={1} value={v} onChange={e=>updatePin(i,e.target.value)} onKeyDown={e=>pinKey(i,e)} className="h-[74px] w-[74px] rounded-xl border border-cyan-400 bg-[#06172f]/90 text-center text-2xl font-bold outline-none focus:shadow-[0_0_18px_rgba(34,211,238,.35)]"/>)}</div>
      <button type="button" onClick={handlePinLogin} disabled={pinLoading} className="mt-5 flex w-full items-center justify-center gap-3 rounded-xl border border-cyan-300/80 bg-[#07376f]/75 py-4 text-base font-bold shadow-[0_0_22px_rgba(14,165,233,.30)] hover:bg-[#0a478d] disabled:opacity-60"><LockKeyhole className="h-5 w-5"/>{pinLoading?"Logowanie...":"Zaloguj się kodem PIN"}</button>
      <div className="mt-4 text-sm text-slate-300">Nie masz kodu PIN? <button type="button" onClick={()=>{setCreateError("");setCreateSuccess("");setCreateOpen(true)}} className="ml-2 font-bold text-cyan-300 hover:text-cyan-200">Utwórz PIN ›</button></div></div>
      <Link href="/" className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl border border-sky-400/50 bg-[#06172f]/75 py-4 font-semibold text-sky-200"><ArrowLeft className="h-5 w-5"/>Wróć do strony głównej</Link>
    </div></div>

    {twoFactorOpen?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 px-4 backdrop-blur-sm"><div className="w-full max-w-[430px] rounded-2xl border border-cyan-400/70 bg-[#04172f] p-6 shadow-[0_0_45px_rgba(14,165,233,.30)]"><h2 className="text-xl font-bold">Weryfikacja dwuetapowa</h2><p className="mt-2 text-sm text-slate-400">Wpisz 6-cyfrowy kod z Google Authenticator lub Microsoft Authenticator.</p><input autoFocus inputMode="numeric" maxLength={6} value={twoFactorCode} onChange={e=>setTwoFactorCode(e.target.value.replace(/\D/g,"").slice(0,6))} onKeyDown={e=>{if(e.key==="Enter")verifyTwoFactor()}} placeholder="000000" className="mt-5 w-full rounded-xl border border-cyan-400/50 bg-[#06172f] px-4 py-4 text-center text-2xl tracking-[.45em] outline-none focus:border-cyan-300"/>{twoFactorError?<div className="mt-3 rounded-xl border border-rose-400/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{twoFactorError}</div>:null}<button type="button" onClick={verifyTwoFactor} disabled={twoFactorLoading} className="mt-4 w-full rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 py-3.5 font-bold shadow-[0_0_24px_rgba(14,165,233,.28)] disabled:opacity-60">{twoFactorLoading?"Weryfikacja...":"Potwierdź kod 2FA"}</button><button type="button" onClick={()=>{setTwoFactorOpen(false);setTwoFactorCode("")}} className="mt-3 w-full py-2 text-sm text-slate-400">Anuluj</button></div></div>:null}

    {createOpen?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4 backdrop-blur-sm"><div className="w-full max-w-[480px] rounded-2xl border border-cyan-400/70 bg-[#04172f] p-6 shadow-[0_0_45px_rgba(14,165,233,.30)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Utwórz kod PIN</h2><p className="mt-1 text-xs text-slate-400">Potwierdź konto hasłem i ustaw 4-cyfrowy PIN.</p></div><button onClick={()=>setCreateOpen(false)} className="rounded-lg border border-white/10 p-2 text-slate-300"><X className="h-5 w-5"/></button></div><div className="space-y-3"><div className="rounded-xl border border-sky-400/25 bg-[#06172f] px-4 py-3 text-sm text-slate-300">{email||"Najpierw wpisz e-mail na ekranie logowania"}</div><input type="password" value={createPassword} onChange={e=>setCreatePassword(e.target.value)} placeholder="Hasło do konta" className="w-full rounded-xl border border-sky-400/40 bg-[#06172f] px-4 py-3 outline-none focus:border-cyan-300"/><input inputMode="numeric" maxLength={4} value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,"").slice(0,4))} placeholder="Nowy PIN — 4 cyfry" className="w-full rounded-xl border border-sky-400/40 bg-[#06172f] px-4 py-3 outline-none focus:border-cyan-300"/><input inputMode="numeric" maxLength={4} value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,"").slice(0,4))} placeholder="Powtórz PIN" className="w-full rounded-xl border border-sky-400/40 bg-[#06172f] px-4 py-3 outline-none focus:border-cyan-300"/>{createError?<div className="rounded-lg bg-rose-500/10 px-3 py-2 text-sm text-rose-300">{createError}</div>:null}{createSuccess?<div className="rounded-lg bg-emerald-500/10 px-3 py-2 text-sm text-emerald-300">{createSuccess}</div>:null}<button type="button" onClick={createPin} disabled={createLoading} className="w-full rounded-xl bg-[linear-gradient(90deg,#12c7e9,#2454ff)] py-3.5 font-bold shadow-[0_0_24px_rgba(14,165,233,.28)] disabled:opacity-60">{createLoading?"Tworzenie...":"Utwórz PIN"}</button></div></div></div>:null}
  </main>
}
