import type React from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ShieldCheck, Target, TrendingDown, TrendingUp } from "lucide-react";
export type StrategyConfig={name:string;tagline:string;timeframe:string;market:string;hero:string;buy:string;sell:string;buyConfirm:string;sellConfirm:string;rules:string[];buyRules:string[];sellRules:string[];checklist:string[]};
export default function StrategyPage({c}:{c:StrategyConfig}){return <main className="min-h-screen bg-[#020817] p-3 text-white md:p-6"><div className="mx-auto max-w-[1700px]">
<Link href="/strategie" className="inline-flex items-center gap-2 rounded-xl border border-sky-400/20 bg-sky-500/10 px-3 py-2 text-xs text-sky-200"><ArrowLeft className="h-4 w-4"/> Wszystkie strategie</Link>
<section className="mt-3 overflow-hidden rounded-[22px] border border-sky-400/25 bg-[linear-gradient(135deg,#0b4c83,#06284c)] p-5"><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr] xl:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-sky-300">FX TRADE • STRATEGIA</div><h1 className="mt-2 text-3xl font-black md:text-4xl">{c.name}</h1><p className="mt-3 text-sm leading-6 text-sky-100/65">{c.tagline}</p><div className="mt-5 flex flex-wrap gap-2"><Chip>Interwał: {c.timeframe}</Chip><Chip>Rynek: {c.market}</Chip><Chip>Minimalne RR: 1:1.5</Chip></div></div><Pic src={c.hero} alt={`${c.name} — schemat strategii`} hero/></div></section>
<section className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{c.rules.map((r,i)=><div key={r} className="rounded-2xl border border-white/10 bg-[#071522] p-4"><div className="text-[10px] font-black text-sky-300">KROK {i+1}</div><div className="mt-2 text-xs leading-5 text-slate-300">{r}</div></div>)}</section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><Side title="SETUP BUY" icon={<TrendingUp className="h-5 w-5 text-emerald-300"/>} image={c.buy} confirm={c.buyConfirm} rules={c.buyRules}/><Side title="SETUP SELL" icon={<TrendingDown className="h-5 w-5 text-red-300"/>} image={c.sell} confirm={c.sellConfirm} rules={c.sellRules}/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-[1fr_.55fr]"><div className="rounded-[18px] border border-sky-400/15 bg-[#071522] p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-sky-300"/> CHECKLISTA PRZED WEJŚCIEM</div><div className="mt-4 grid gap-3 md:grid-cols-2">{c.checklist.map(x=><div key={x} className="flex gap-2 text-xs leading-5 text-slate-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>{x}</div>)}</div></div><div className="rounded-[18px] border border-amber-400/20 bg-amber-500/[.06] p-5"><div className="flex items-center gap-2 font-black text-amber-200"><Target className="h-5 w-5"/> ZARZĄDZANIE</div><p className="mt-3 text-xs leading-5 text-slate-300">SL za logiczną strukturą lub świecą unieważniającą. TP planuj przed wejściem. Gdy nie ma minimum 1:1.5, setup pomijamy.</p></div></section>
</div></main>}
function Chip({children}:{children:React.ReactNode}){return <span className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-[11px] text-sky-100/75">{children}</span>}
function Pic({src,alt,hero=false}:{src:string;alt:string;hero?:boolean}){return <div className={`relative overflow-hidden rounded-2xl border border-white/10 bg-[#020a13] ${hero?'h-[300px] md:h-[360px]':'h-[360px] md:h-[430px]'}`}><Image src={src} alt={alt} fill className="object-contain object-center p-2" sizes="(max-width:1280px) 100vw,50vw"/></div>}
function Side({title,icon,image,confirm,rules}:{title:string;icon:React.ReactNode;image:string;confirm:string;rules:string[]}){return <div className="rounded-[20px] border border-white/10 bg-[#06111d] p-4"><div className="flex items-center gap-2 text-lg font-black">{icon}{title}</div><div className="mt-3 grid gap-3 2xl:grid-cols-[1.35fr_.65fr]"><Pic src={image} alt={title}/><Pic src={confirm} alt={`${title} — potwierdzenie`}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{rules.map(x=><div key={x} className="flex gap-2 rounded-xl bg-white/[.035] p-3 text-xs leading-5 text-slate-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>{x}</div>)}</div></div>}
